org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
org.gradle.configuration-cache=false

fabric.loom.multiProjectOptimisation=true

minecraft_version=1.21.1
loader_version=0.19.2
fabric_api_version=0.116.11+1.21.1
fabric_kotlin_version=1.13.10+kotlin.2.3.20

maven_group=com.macuguita.daisy
archives_base_name=daisy-server-utilities

# Dependencies
modmenu_version=11.0.4
server_translations_api_version=2.3.1+1.21-pre2
kaleido_config_version=0.3.3+1.3.2
sgui_version=1.6.1+1.21.1
kord_version=0.18.1
ktor_version=3.4.0

daisy-server-utilities-version=0.0.1-SNAPSHOT
daisy-base-version=0.0.1-SNAPSHOT
daisy-tpa-version=0.0.1-SNAPSHOT
daisy-home-version=0.0.1-SNAPSHOT
daisy-warp-version=0.0.1-SNAPSHOT
daisy-player-management-version=0.0.1-SNAPSHOT
daisy-discord-version=0.0.1-SNAPSHOT
