org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=false

minecraft_version=1.21.1
loader_version=0.18.4
fabric_api_version=0.116.9+1.21.1
fabric_kotlin_version=1.13.9+kotlin.2.3.10

mod_version=1.0.0
maven_group=com.macuguita.daisy
archives_base_name=daisy-server-utilities

# Dependencies
modmenu_version=11.0.3

daisy-base-version=1.0.0
daisy-tpa-version=1.0.0
daisy-home-version=1.0.0
daisy-warp-version=1.0.0
